name: dApp

permissions: {}

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build frontend dApp
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci
        working-directory: frontend/dapp

      - name: Build
        run: npm run build
        working-directory: frontend/dapp
